### ISSUE TITLE
Busy spinner doesn't work when button in shadow root

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/sm-ui-button#7]
Animations are occasionally crashing apps, and visually being buggy. My hunch is that it's something to do with getting computed values before the element is displayed, then using them again as they're cached.

To test that theory, just need to check if element is visible before doing any of the animation ever

**Comment by seaneking** [comment]
This is due to shady, updating the title

**Comment by seaneking** [comment]
Fixed in https://github.com/SimplaElements/sm-ui-button/commit/7ac2be6e76062bb0994b4e03ce033f65d6ea1716
